CC=gcc
CFLAGS= -Wall -std=c99
TARGET = fs

all: $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	$(RM) $(TARGET)
	$(RM) a.out
	$(RM) file2.c
	$(RM) file4.c
	$(RM) lab1.jav
	$(RM) file1.c
	$(RM) file3.c
	$(RM) lab2.jav
