all: 
	gcc -g -Wall -o batch_scheduler batch_scheduler.c
	gcc -g -Wall -o process_termination process_termination.c
	gcc -g -Wall -o process_creation process_creation.c
 
clean: 
	rm batch_scheduler
	rm process_termination
	rm process_creation

